---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmetic-d6acbb38
  labels:
    app: cosmetic-d6acbb38
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: cosmetic-d6acbb38
  template:
    metadata:
      labels:
        app: cosmetic-d6acbb38
    spec:
      containers:
        - name: cosmetic-d6acbb38
          image: docker.io/phengbunath/cosmetic-d6acbb38:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
