---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmetic-d6acbb38                  # Ingress name
  labels:
    app: cosmetic-d6acbb38
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "cosmetic-d6acbb38.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cosmetic-d6acbb38               # Links to Service name dynamically
                port:
                  number: 3000  # Links to service port dynamically
